- hosts: centos
  roles:
  - centos-base
  - distribute_images
  - networks

- hosts: virtual_appliances
  gather_facts: no
  roles:
  - remove_virtual_appliances
  - build_virtual_appliances

- hosts: centos
  roles:
  - dhcpd

- hosts: virtual_appliances
  gather_facts: no
  roles:
  - first_contact



