- hosts: centos
  roles:
  - name: centos-base
    become: True
  - distribute_images
  - networks

- hosts: virtual_appliances
  gather_facts: no
  roles:
  - remove_virtual_appliances
  - build_virtual_appliances

- hosts: centos
  roles:
  - name: dhcpd
    become: True

- hosts: virtual_appliances
  gather_facts: no
  roles:
  - first_contact
