- hosts: centos
  roles:
  - name: centos-base
    become: True
  - distribute_images
  - networks

- hosts: virtual_appliances
  gather_facts: no
  pre_tasks:
  - group_by:
      key: "seq_{{ host }}"
    delegate_to: localhost
  roles:
  - remove_virtual_appliances
  - build_virtual_appliances

- hosts: centos
  roles:
  - name: dhcpd
    become: True

- hosts: virtual_appliances
  gather_facts: no
  serial: 1
  roles:
  - prep_localhost

- hosts: virtual_appliances
  gather_facts: no
  roles:
  - first_contact

- hosts: dns_server
  gather_facts: no
  roles:
  - dns_masq