all:
  hosts:
    localhost:
      ansible_sudo_pass: "{{ lookup('env', 'ansible_sudo_pass') }}"
    dns_server:
      ansible_ssh_host: dg.cidrblock.net
      ansible_user: root
      ansible_ssh_pass: "{{ lookup('env', 'ansible_sudo_pass') }}"
  children:
    centos:
      hosts:
        one:
        two:
    virtual_appliances:
      children:
        ones_virtual_appliances:  # name has to match a host xxx_
          hosts:
            eos101:
            eos102:
            eos103:
            eos104:
            nxos101:
            nxos102:
            nxos103:
            nxos104:
            ios101:
            ios102:
            ios103:
            ios104:
            vyos101:
            vyos102:
            vyos103:
            vyos104:
          vars:
            host: one
        twos_virtual_appliances: # name has to match a host xxx_
          hosts:
            eos201:
            eos202:
            eos203:
            eos204:
            nxos201:
            nxos202:
            nxos203:
            nxos204:
            ios201:
            ios202:
            ios203:
            ios204:
            vyos201:
            vyos202:
            vyos203:
            vyos204:
          vars:
            host: two
