- name: List the existing networks
  virt_net:
    command: list_nets
  become: true
  register: nets

- name: Output the existing networks
  debug:
    var: nets
  when: "ansible_verbosity >= 2"

- name: Build each network
  include: network.yml
  with_items:
  - default
  - inside