- name: "Destroy the {{ item }} network"
  virt_net:
    command: destroy
    name: "{{ item }}"
  when: "item in ansible_libvirt_networks and ansible_libvirt_networks[item]['state'] == 'active'"
  changed_when: True
  ignore_errors: True

- name: "Undefine the {{ item }} network"
  virt_net:
    command: undefine
    name: "{{ item }}"
  when: "item in ansible_libvirt_networks"
  changed_when: True

- name: "Define the {{ item }} network"
  virt_net:
    command: define
    name: "{{ item }}"
    xml: "{{ lookup('template', '{{ item }}.xml.j2') }}"
  changed_when: True

- name: "Start the {{ item }} network"
  virt_net:
    command: start
    name: "{{ item }}"
  changed_when: True

- name: "Autostart the {{ item }} network"
  virt_net:
    autostart: yes
    name: "{{ item }}"

- name: "Get the {{ item }} network config"
  shell: "/usr/sbin/ip -d link sh {{ item|regex_replace('-', '_') }}"
  register: net_info

- name: "Enable lldp on the {{ item }} network"
  shell: "/usr/sbin/ip link set {{ item|regex_replace('-', '_') }} type bridge group_fwd_mask 0x4000"
  when: "'group_fwd_mask 0x4000' not in net_info['stdout']"
  become: True
