- name: Get all virtual appliances
  virt:
    command: list_vms
  register: list_vms
  become: true
  delegate_to: "{{ host }}"

- name: Get the info for each
  virt:
    name: "{{ inventory_hostname }}"
    command: info
  when: "inventory_hostname in list_vms['list_vms']"
  register: veos
  become: true
  delegate_to: "{{ host }}"

- name: Destroy the virtual appliance
  virt:
    name: "{{ inventory_hostname }}"
    command: destroy
  when: "inventory_hostname in list_vms['list_vms'] and veos is defined and veos[inventory_hostname]['state'] == 'running'"
  become: true
  delegate_to: "{{ host }}"
  changed_when: True

- name: Undefine the virtual appliance
  virt:
    name: "{{ inventory_hostname }}"
    command: undefine
  when: "inventory_hostname in list_vms['list_vms']"
  become: true
  delegate_to: "{{ host }}"
  changed_when: True

- name: Set a fact for the qcow2 file
  set_fact:
      qcow: "{{ vm_directory }}/{{ inventory_hostname  + '.qcow2' }}"
  delegate_to: "{{ host }}"

- name: Check that the qcow2 exists
  stat:
    path: "{{ qcow }}"
  delegate_to: "{{ host }}"
  register: qcow_stat

- name: Delete the qcow2 file
  file:
    path: "{{ qcow }}"
    state: absent
  when: qcow_stat['stat']['exists']
  delegate_to: "{{ host }}"

