ansible_sudo_pass: "{{ lookup('env', 'ansible_sudo_pass') }}"

net_mgmt: "192.168.{{ groups['centos']['index'](inventory_hostname) + 101 }}.0/24"
net_mgmt_bridge_name: net_mgmt
net_inside_bridge_name: net_inside