- name: Convert the vmdk file for each eos virtual appliance
  shell: "qemu-img convert -f vmdk -O qcow2 {{ vm_directory }}/{{ images['eos']['vmdk']['name'] }} {{ qcow }}"
  delegate_to: "{{ host }}"
  become: true

- name: Template out the initial config file for each eos virtual appliance
  template:
    src: eos_config.j2
    dest: "{{ vm_directory }}{{ inventory_hostname }}.cfg"
  delegate_to: "{{ tftp_server }}"