
- name: Install the lxml pip package
  pip:
    name:
    - lxml

- name: Add the user to the libvirt group
  user:
    name: "{{ lookup('env','USER') }}"
    groups: libvirt
    append: True

- name: Include the step for the UEFI BIOS installation
  include: uefi_bios.yml

- name: Install qemu-ev
  include: qemu_ev.yml

- name: Install the tftp server on the tftp host
  include: tftp_server.yml
  when: inventory_hostname_short == tftp_server
