id: "{{ groups[host + 's_virtual_appliances']['index'](inventory_hostname) + 10 }}"
vnc_port: '{{ 5900 + id|int }}'
telnet_port: '{{ 2000 + id|int }}'
ansible_ssh_host: "{{ hostvars[host]['net_mgmt']|ipaddr('network')|ipmath(id|int) }}"
ansible_user: "{{ initial_virtual_appliance_users[0]['name'] }}"
ansible_connection: network_cli
ansible_password: "{{ initial_virtual_appliance_users[0]['password'] }}"
ansible_become: True
ansible_become_method: enable
ansible_become_pass: "{{ initial_virtual_appliance_users[0]['password'] }}"
ansible_network_os: "{{ inventory_hostname[0:-3] }}"

initial_virtual_appliance_users:
- name: admin
  password: password
- name: bthornto
  password: password
