- name: Copy eos images
  synchronize: 
    src: "{{ item['value']['path'] }}/{{ item['value']['name'] }}"
    dest: "{{ vm_directory }}"
  delegate_to: "{{ item['value']['host'] }}"
  with_dict: "{{ images['eos'] }}"
  loop_control:
    label: "{{ item['value']['name'] }}"



- name: Install the lxml pip package
  pip:
    name:
    - lxml
  become: true

- name: List the existing networks
  virt_net:
    command: list_nets
  become: true
  register: nets

- name: Output the existing networks
  debug:
    var: nets
  when: "ansible_verbosity >= 2"

- name: Get the xml for the default network
  virt_net:
    command: get_xml
    name: default
  become: true
  register: default_xml
  when: "'default' in nets['list_nets']"

- name: Output the xml for the default network
  debug:
    var: default_xml
  when: "'default' in nets['list_nets'] and ansible_verbosity >= 2"

- name: Destroy the default network
  virt_net:
    command: destroy
    name: default
  become: true
  when: "'default' in nets['list_nets']"

- name: Undefine the default network
  virt_net:
    command: undefine
    name: default
  become: true
  when: "'default' in nets['list_nets']"

- name: Define the default network
  virt_net:
    command: define
    name: default
    xml: "{{ lookup('template', 'default_network.xml.j2') }}"
  become: true

- name: Start the default network
  virt_net:
    command: start
    name: default
  become: true

- name: Enable lldp
  shell: echo 16384 > /sys/class/net/virbr0/bridge/group_fwd_mask
  become: true