- name: Add an entry to the localhost hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "^.*{{ inventory_hostname }}.*$"
    line: "{{ ansible_ssh_host }}    {{ inventory_hostname }}"
  delegate_to: localhost
  become: True

- name: Remove the ssh key for each virtual appliance name
  shell: "ssh-keygen -R {{ inventory_hostname }}"
  delegate_to: localhost
  ignore_errors: True

- name: Remove the ssh key for each virtual appliance ip
  shell: "ssh-keygen -R {{ ansible_ssh_host }}"
  delegate_to: localhost
  ignore_errors: True