- name: Remove the ssh key for each virtual appliance name
  shell: "ssh-keygen -R {{ inventory_hostname }}"
  delegate_to: localhost
  ignore_errors: True

- name: Remove the ssh key for each virtual appliance ip
  shell: "ssh-keygen -R {{ ansible_ssh_host }}"
  delegate_to: localhost
  ignore_errors: True
