

vm_directory: /mnt/space/vms/
tftp_server: one

images:
  eos:
    vmdk:
      name: vEOS-lab-4.21.1.1F.vmdk
      path: /mnt/space/isos
      host: one
    iso:
      name: Aboot-veos-8.0.0.iso
      path: /mnt/space/isos
      host: one
  nxos:
    qcow2:
      name: nxosv.9.2.2.qcow2
      path: /mnt/space/isos
      host: one
  ios:
    qcow2:
      name: csr1000v-universalk9.03.12.00.S.154-2.S-std.qcow2
      path: /mnt/space/isos
      host: one

dhcp:
  domain_name: cidrblock.net
  dns_server: 192.168.86.1
